apiVersion: v1
kind: Pod 
metadata:
  name: game 
  labels:
   app: game
  namespace: ac 
spec: 
  containers: 
   - name: gameak
     image: blackicebird/2048:latest 
     ports:
     - containerPort: 80
       protocol: TCP 
       
