apiVersion: v1
kind: Pod
metadata: 
     name: 2048
     labels: 
      app: new_app
spec:
   containers:
    - name: 2048game
      image: blackicebird/2048:latest
      ports:
      - containerPort: 80
        protocol: TCP
       
