apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: daemon
    labels:
      app: acapp
spec:
    selector:
      matchLabels:
          app: acapp
    template:
      metadata:
        labels:
          name: cwatch
          app: acapp
      spec:
        containers:
         - name : cwatch
           image: amazon/cloudwatch-agent:latest
           ports:
             - containerPort: 80
               protocol: TCP