apiVersion: apps/v1
kind: Daemonset
metadata:
    name: deamon
    labels:
      app: acapp
spec:
    selector:
      matchlabels:
        app: acapp
    template:
      metadata:
      labels:
        name: cwatch
        app: acapp
      spec:
        containers:
         - name : cwatch
           image: amazon/cloudwatch-agent
           ports:
             - containerPort: 80
               protocol: TCP