apiVersion: apps/V1
kind:  Deployment
metadata:
  name: deploy
  labels:
    app: depapp
spec:
    strategy:
      type: Rolllingupdate
      rollingupdate:
            maxsure: 1
            Maxunavailable: 1
      selector:
        matchlabels: 
            app: depapp
      replicas: 4
      template: 
        metadata:
          labels:
            name: nginxapp
            app: depapp
        spec: 
          containers:
            - name: nginxapp
              image: nginx:latest
              ports: 
                  - containersPort: 80
                    protocol: TCP


          
       