apiVersion: apps/v1
kind:  Deployment
metadata:
  name: deploy
  labels:
    app: acapp
spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
            maxSurge: 2
            maxUnavailable: 4
    selector:
      matchLabels: 
          app: acapp
    replicas: 10
    template: 
      metadata:
        labels:
          name: nginxapp
          app: acapp
      spec: 
        containers:
          - name: nginxapp
            image: tomcat:latest
            ports: 
                - containerPort: 80
                  protocol: TCP


          
       