apiVersion: v1
kind: Service
metadata:
    name: mygame-svs
spec:
    selector: 
       app: new_app
    type: NodePort
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          name: 2048