apiVersion: v1
kind: Service 
metadata: 
   name: akservice 
   namespace: ac 
spec:
  selector:
    app: game
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: gameak