apiVersion: v1
kind: Service
metadata:
    name: mygame-svs
spec:
    selector: 
       app: new_app
    ports:
        - protocol: TCP
          port: 80
          targetport: 80
          type:   LoadBalancer