apiVersion: v1
kind: Pod
metadata: 
  name: acpod
  namespace: ac
  labels:
    app: myapp
spec:
    containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort : 80
            protocol : TCP
---
apiVersion: v1
kind: Service
metadata: 
    name: b24services
    namespace: ac
spec: 
    type: NodePort
    selector:
      app: myapp
    ports:
        - port: 80
          targetPort: 80
          protocol: TCP
          name: nginx
...