apiVersion: apps/v1
kind: repliaset
metadata:
    name: rs
    labels:
      app: rsapp
spec:
      selector:
      replicas: 4
      template:
        metadata:
          labels:
            name: nginxapp
            app:  rsapp
        spec:
          containers:
            - name: nginxapp
              image: nginx:latest
              ports: 
                  - containersPort: 80
                    protocol: TCP
                    
      