apiVersion: v1
kind: ReplicationController
metadata: 
  name: rpc
  labels:
    apps: rpcapp
spec:
    selector:
      app: rpcapp
    replicas: 4
    template:
      metadata:
        labels:
          name: nginxapp
          app:  rpcapp
      spec:
        containers:
          - name: nginxapp
            image: nginx:latest
            ports: 
                - containerPort: 80
                  protocol: TCP
                  
