
apiVersion: v1
kind: Service
metadata:
  name: snake-service
  labels:
    app: snake-game
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
  selector:
    matchLabels:
      app: snake-game