
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deapp
  labels:
    app: configapp
spec:
  selector:
    matchLabels:
      app: deapp
  replicas: 4
  template:
    metadata:
      labels:
        name: mdb
        app: deapp
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: rootac
                        